# Site wide configuration

title: Felipe Rank - Front-end Developer
description: My name is Felipe rank and I'm front-end developer
url: 
background: build/images/1.jpg

gems:
  - jekyll-sitemap

# Site owner
owner:
  name: Felipe Rank
  email: raank92@gmail.com
  twitter: http://goo.gl/I6sd9O
  facebook: http://goo.gl/umWfeX
  linkeding: http://goo.gl/5V2l5R
  medium: http://goo.gl/rKAXVt
  avatar: build/images/profile.jpg

exclude: ["lib", "app", "assets", "bower.json", "gulpfile.js","config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
