# Site wide configuration
title: Felipe Rank
description: Desenvolvedor Jr front e back end, especialista em wordpress
analytics: UA-54717879-1
url: https://raank.github.io
baseurl: /
source:      .
destination: ./_site
includes:     ./_includes
layouts:     ./_layouts
data_source: ./_data
share: images/share/share.jpg

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
highlighter: pygments

# Outputting
permalink:     /blog/:year/:month/:title.html
paginate: 5
paginate_path: "/blog/page:num/"
timezone:      null

# collections
collections:
  projects:
    output: true
    permalink: /projetos/:title.html
    layout: project.html

# dep
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Felipe Rank
  email: raank92@gmail.com
  twitter: http://goo.gl/I6sd9O
  facebook: http://goo.gl/umWfeX
  linkedin: http://goo.gl/5V2l5R
  github: https://github.com/raank

# Meta Tags
metatag:
  description: Felipe Rank
  tags: Felipe Rank, Desenvolvimento, Criação de Sites em Jaraguá do Sul, desenvolvimento de sites
  type: website

# excludes files
exclude: ["lib", "app", "assets", "csscomb.json", "bower.json", "gulpfile.js","config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
